spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
    gateway:
      discovery:
        locator:
          enabled: true
          
      routes:
        - id: tsg-auth
          uri: lb://tsg-auth
          predicates:
            - Path=/api/tsg-auth/public/**
          filters:
            - StripPrefix=2
            - RewritePath=/api/tsg-auth/public/(?<segment>.*), /$\{segment}

        - id: tsg-auth
          uri: lb://tsg-auth
          predicates:
            - Path=/api/tsg-auth/user/**
          filters:
            - name: UsuarioAuthorizationFilter 
            - StripPrefix=2
            - RewritePath=/api/tsg-auth/user/(?<segment>.*), /$\{segment}

        - id: tsg-posts
          uri: lb://tsg-posts
          predicates:
            - Path=/api/tsg-posts/user/**
          filters:
            - name: UsuarioAuthorizationFilter 
            - StripPrefix=2
            - RewritePath=/api/tsg-posts/user/(?<segment>.*), /$\{segment}



 
